In [25]:
import pandas as pd 
from sklearn.model_selection import train_test_split

df= pd.read_csv("cleaned-2.csv")
df

,Unnamed: 0,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,business_or_commercial,loan_amount,rate_of_interest,...,credit_type,Credit_Score,LTV,Status,dtir1,loan_to_income,loan_to_collateral,interest_burden,total_cost_proxy,risk_score
0,0,cf,Sex Not Available,nopre,type1,p1,l1,nob/c,116500,3.990,...,EXP,758,98.728814,1,45.0,66.916,0.987,464835.0,467526.13,-16.8
1,1,cf,Male,nopre,type2,p1,l1,b/c,206500,3.990,...,EQUI,552,75.297619,1,40.0,41.458,0.494,823935.0,826626.13,104.8
2,2,cf,Male,pre,type1,p1,l1,nob/c,406500,4.560,...,EXP,834,80.019685,0,46.0,42.875,0.800,1853640.0,1854235.00,-62.0
3,3,cf,Male,nopre,type1,p4,l1,nob/c,456500,4.250,...,EXP,587,69.376900,0,42.0,38.423,0.694,1940125.0,1942816.13,84.6
4,4,cf,Joint,pre,type1,p1,l1,nob/c,696500,4.000,...,CRIF,602,91.886544,0,39.0,66.708,0.919,2786000.0,2786000.00,74.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1504,1504,cf,Joint,pre,type3,p1,l1,nob/c,236500,4.375,...,CIB,533,99.369748,0,44.0,40.214,0.994,1034687.5,1036987.50,117.8
1505,1505,cf,Sex Not Available,nopre,type3,p3,l1,nob/c,196500,3.990,...,EQUI,834,75.297619,1,40.0,72.751,0.470,784035.0,786726.13,-64.4
1506,1506,cf,Male,nopre,type2,p4,l1,b/c,116500,3.990,...,EXP,624,73.734177,1,26.0,49.765,0.737,464835.0,467526.13,56.0
1507,1507,cf,Male,nopre,type1,p3,l1,nob/c,136500,3.990,...,EXP,840,72.606383,0,38.0,45.485,0.726,544635.0,547745.38,-68.8


In [27]:
df.dtypes[df.dtypes == 'object']

Series([], dtype: object)

In [28]:
print(X_train.dtypes)

Unnamed: 0                  int64
Gender                        str
approv_in_adv                 str
loan_type                     str
loan_purpose                  str
Credit_Worthiness             str
business_or_commercial        str
loan_amount                 int64
rate_of_interest          float64
Interest_rate_spread      float64
Upfront_charges           float64
term                      float64
Neg_ammortization             str
interest_only                 str
lump_sum_payment              str
property_value            float64
construction_type             str
occupancy_type                str
Secured_by                    str
total_units                   str
income                    float64
credit_type                   str
Credit_Score                int64
LTV                       float64
dtir1                     float64
loan_to_income            float64
loan_to_collateral        float64
interest_burden           float64
total_cost_proxy          float64
risk_score    

In [29]:
# remove useless index column
df = df.drop("Unnamed: 0", axis=1)

# convert all object/string columns
df = pd.get_dummies(df, drop_first=True)

In [31]:
X= df.drop("Status", axis=1 )
y=df["Status"]
X_train, X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state= 42, stratify=y )
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [32]:
from sklearn.preprocessing import StandardScaler
print(X_train.dtypes[X_train.dtypes == 'object'])
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
from sklearn.svm import SVC

svm_linear = SVC(
    kernel='linear',
    C=1,
    class_weight='balanced'
)

svm_linear.fit(X_train_scaled, y_train)

Series([], dtype: object)


,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'linear'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide `.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide `.",False
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",'balanced'
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [33]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
y_pred_lin = svm_linear.predict(X_test_scaled)

print("=== SVM Linear ===")
print(classification_report(y_test, y_pred_lin))
print(confusion_matrix(y_test, y_pred_lin))

=== SVM Linear ===
              precision    recall  f1-score   support

           0       0.87      0.88      0.87       227
           1       0.62      0.60      0.61        75

    accuracy                           0.81       302
   macro avg       0.74      0.74      0.74       302
weighted avg       0.81      0.81      0.81       302

[[199  28]
 [ 30  45]]


In [36]:
svm_rbf = SVC(
    kernel='rbf',
    C=1,
    gamma=0.01,
    class_weight='balanced'
)

svm_rbf.fit(X_train_scaled, y_train)

y_pred_rbf = svm_rbf.predict(X_test_scaled)

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred_rbf))
print(confusion_matrix(y_test, y_pred_rbf))

              precision    recall  f1-score   support

           0       0.87      0.92      0.89       227
           1       0.70      0.60      0.65        75

    accuracy                           0.84       302
   macro avg       0.79      0.76      0.77       302
weighted avg       0.83      0.84      0.83       302

[[208  19]
 [ 30  45]]


In [37]:
svm_rbf = SVC(
    kernel='rbf',
    C=10,
    gamma=0.1,
    class_weight='balanced'
)

svm_rbf.fit(X_train_scaled, y_train)

y_pred_rbf = svm_rbf.predict(X_test_scaled)

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred_rbf))
print(confusion_matrix(y_test, y_pred_rbf))

              precision    recall  f1-score   support

           0       0.82      0.95      0.88       227
           1       0.72      0.39      0.50        75

    accuracy                           0.81       302
   macro avg       0.77      0.67      0.69       302
weighted avg       0.80      0.81      0.79       302

[[216  11]
 [ 46  29]]


In [38]:
svm_rbf = SVC(
    kernel='rbf',
    C=5,
    gamma=0.01,
    class_weight='balanced'
)

svm_rbf.fit(X_train_scaled, y_train)

y_pred_rbf = svm_rbf.predict(X_test_scaled)

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred_rbf))
print(confusion_matrix(y_test, y_pred_rbf))

              precision    recall  f1-score   support

           0       0.90      0.90      0.90       227
           1       0.70      0.69      0.70        75

    accuracy                           0.85       302
   macro avg       0.80      0.80      0.80       302
weighted avg       0.85      0.85      0.85       302

[[205  22]
 [ 23  52]]


In [39]:
svm_rbf = SVC(
    kernel='rbf',
    C=1,
    gamma=0.001,
    class_weight='balanced'
)

svm_rbf.fit(X_train_scaled, y_train)
y_pred_rbf = svm_rbf.predict(X_test_scaled)

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred_rbf))
print(confusion_matrix(y_test, y_pred_rbf))

              precision    recall  f1-score   support

           0       0.85      0.97      0.91       227
           1       0.85      0.47      0.60        75

    accuracy                           0.85       302
   macro avg       0.85      0.72      0.75       302
weighted avg       0.85      0.85      0.83       302

[[221   6]
 [ 40  35]]


In [ ]:
# best result turns out to be when the c=5 and gamma = 0.01 as the FN false negatives are the least recallls for [1] defaulters are highest and f1 score is also good.
